### ISSUE TITLE
Global admin field always "nej" - only cosmetic

### ISSUE THREAD

**Issue by ALionTiger** [OS2iot/OS2iot-frontend#119]
### Beskriv fejlen // Describe the bug
The global admin field under user details is always "nej 

### Genskab fejlen // To Reproduce
Sådan genskabes fejlen // Steps to reproduce the behavior:
1. Go to 'brugere'
2. Click on 'a user with admin rights'
3. Scroll down to 'global administrator'

### Forventet funktion // Expected behavior
Expected that it would follow what rights a user has, like in the user table view

![screenshot]("https://aarhuskommune-my.sharepoint.com/:i:/g/personal/danmo_aarhus_dk/EaFXi8Oc6CdCk_4fZdD_ubQB69p7zIu5tIoZ56fyqoVrIg?e=Q34YKF "Screenshot")

### URL
Angiv den URL, som fejlen opstår på - fx [link](https://prod.os2iot.kmd.dk/admin/users/3)

### Desktop
Udfyld venligst følgende // Please complete the following information:
    Styresystem/OS: MacOS
    Browser: Chrome

**Comment by ramogens** [comment]
Thanks for reporting this, @ALionTiger. I've submitted a bug report in JIRA: https://os2web.atlassian.net/browse/IOT-1414

**Comment by ramogens** [comment]
This bug was fixed in the fall of 2023 with [v1.6.0](https://github.com/OS2iot/OS2iot-backend/releases/tag/v1.6.0)
