### ISSUE TITLE
baseUrl should not be hardcoded in Docker image

### ISSUE THREAD

**Issue by marcinkoperski** [OS2iot/OS2IoT-frontend#44]
Please make baseUrl parameter configurable as environmental variable:
https://github.com/OS2iot/OS2IoT-frontend/blob/master/src/environments/environment.prod.ts

**Comment by Joiversen** [comment]
Thank you for contributing @marcinkoperski. We appreciate it!

I have added your issue to OS2iot's backlog, from where it will be handled.
