### ISSUE TITLE
Sorting function shortens list

### ISSUE THREAD

**Issue by ALionTiger** [OS2iot/OS2IoT-frontend#46]
When sorting the device list (Tilknyttede IoT enheder), by clicking on last active (sidst aktiv). The list is shortened, and not sorted by name/time in a descending or ascending order.

![Skærmbillede 2021-09-08 132243](https://user-images.githubusercontent.com/86404358/132503503-845cf559-4205-488f-aae0-027294222256.png)

**Comment by aNorrah** [comment]
We have the same issue.
And by shortened, in our case, it goes from 20 show devices to zero.

**Comment by ramogens** [comment]
Thank you for the bug report. Other users have reported similar issues when sorting lists. We have initiated a fix.
