### ISSUE TITLE
Deleting application in frontend doesn't remove devices from backend.

### ISSUE THREAD

**Issue by aNorrah** [OS2iot/OS2IoT-frontend#47]
When deleting an application through OS2iot's frontend the individual devices - inside said application - doesn't get removed from the backend.

<img width="1680" alt="Screenshot 2021-09-17 at 14 40 03" src="https://user-images.githubusercontent.com/32865088/133784119-8ff839b1-8b12-4c44-ab17-c7ec56af2d21.png">
Thus, when we try to Bulk import the same devices afterwords, they already exist. We therefore cannot add them again without logging into the backend and deleting them manually.

One, at, a, time...

**Comment by ramogens** [comment]
Thank you for the bug report. We have initiated a fix.
