### ISSUE TITLE
List bug in GUI.

### ISSUE THREAD

**Issue by aNorrah** [OS2iot/OS2IoT-frontend#48]
Inside an application with more than 20 units, you are currently unable to refresh and sort the sensors without them disappearing.

We have one application with 49 sensors inside, and we are actively unable to check for activity without the list refusing to show any units.
![Screenshot 2021-09-16 at 14 09 41](https://user-images.githubusercontent.com/32865088/133609812-57ec2d42-506a-4a4b-8b46-5e25f7db012c.png)

![Screenshot 2021-09-16 at 14 09 57](https://user-images.githubusercontent.com/32865088/133609801-f1a54bec-fd74-47be-8698-b1b67e5f78b8.png)

switching to only showing 5 units at a time will 'sometimes' allow us to scroll through.

**Comment by ramogens** [comment]
@aNorrah Thank you for the bug report. I've moved it to the front-end as you proposed. We'll look into it.

**Comment by ramogens** [comment]
Track progress of fix in JIRA (in Danish): https://os2web.atlassian.net/browse/IOT-1187
