### ISSUE TITLE
CSS change to LoRa gateways.

### ISSUE THREAD

**Issue by aNorrah** [OS2iot/OS2IoT-frontend#49]
add change to:

`<mat-tab-body role="tabpanel" class="mat-tab-body ng-tns-c143-15 ng-star-inserted mat-tab-body-active" id="mat-tab-content-0-1" aria-labelledby="mat-tab-label-0-1">
`
So you can see a larger map.

Easy - but not good - fix:

min-height: 1000px;
    overflow: hidden;

**Comment by aNorrah** [comment]
The best fix would be an auto scale, but I am not a style wizard.

Also, note that changing this box also changes the map widget in other contexts, which is less than ideal.

**Comment by ramogens** [comment]
Thank you for the suggestion, @aNorrah. The small map is indeed annoying. I've put the issue in the OS2iot JIRA bug backlog.

**Comment by ramogens** [comment]
Hi @aNorrah 
Finally the gateway map has been made bigger with the release of version 1.4.0.
Thanks for contributing.
Regards
Mogens, OS2iot product coordinator
