### ISSUE TITLE
Gateway list will sometimes load indefinitely.

### ISSUE THREAD

**Issue by aNorrah** [OS2iot/OS2IoT-frontend#50]
Sometimes when asked to show the list of gateways OS2iot will indefinitely load, and never show any gateways.

The only course of action has so far been to swap between Lora profiles and gateways until the problem disappears.

Very inconsistent, cannot reproduce on command.

**Comment by aNorrah** [comment]
<img width="1402" alt="Screenshot 2021-10-11 at 11 14 58" src="https://user-images.githubusercontent.com/32865088/136765506-66307c3c-e36e-4b35-ae6f-02151ac0dcd3.png">

**Comment by ramogens** [comment]
Thanks for reporting the issue, @aNorrah. How many gateways do you have in total? That would be a nice to know when troubleshooting.

**Comment by aNorrah** [comment]
and by Fix, I mean... hack it into a worse option that however delivers livable functionality.

**Comment by ramogens** [comment]
Fix planned to be released in May - track progress: https://os2web.atlassian.net/browse/IOT-1195

**Comment by ramogens** [comment]
This bug has been fixed with the release of vers. 1.1.1. However load times are minimum 10 seconds. A new jira issue has been created to handle this bug: https://os2web.atlassian.net/browse/IOT-1337
