### ISSUE TITLE
When an application fails to load all devices, you cannot reliably add more.

### ISSUE THREAD

**Issue by aNorrah** [OS2iot/OS2IoT-frontend#53]
When you try to add a new device to an application with more than 20 devices - that will now show the list of devices - it is pretty random

<img width="1052" alt="Screenshot 2021-10-26 at 13 01 51" src="https://user-images.githubusercontent.com/32865088/138865777-12c61b90-b28f-4ac5-ac82-a4e551177742.png">

<img width="1164" alt="Screenshot 2021-10-26 at 13 03 08" src="https://user-images.githubusercontent.com/32865088/138865773-dc921b03-f394-4a7c-8473-c1a1fde3fa6c.png">

I've had errors where neither was selectable at all.
if it doesn't allow you to pick profiles or not. It will give you the respectable error if you are unable to select it: 

deviceprofileid must be an uuid 
serviceprofileid must be an uuid

**Comment by ramogens** [comment]
After the release of version 1.0.1 this bug seems to have disappeared because of the fix of #45. However this bug might show up again when you add even more devices, so I'll let it be open for now. And we'll look into improving the integration to Chirpstacks API in the backend.

**Comment by ramogens** [comment]
We haven't heard about this issue since release 1.0.1, so I'm closing it.
