### ISSUE TITLE
Even though more than 20 datatarget is added, only max 20 will be shown

### ISSUE THREAD

**Issue by augusthjerrild** [OS2iot/OS2IoT-frontend#61]
I tried to add more than 20 datatargets and when I reached 21, then it wasn't possible to use pagination to see the next 20. It looks like it only loads 20 datatargets in total. 

![datatargetfail](https://user-images.githubusercontent.com/70511721/146018649-2996a59a-229d-4068-898f-ba0f11dd17f6.png)

**Comment by ramogens** [comment]
Thank you for the bug report @augusthjerrild. I've added it to our maintenance backlog.

**Comment by ramogens** [comment]
This issue will be solved with release 1.2.0 which will change standard number of rows to 25 with possibility to change to 50 or 100.

**Comment by ramogens** [comment]
Version 1.2.0 has been released today, so I'm closing this issue.
